spring.application.name=library-management-system

# ============================
# SERVER
# Local par 8081, Render par apna PORT use hoga
# ============================
server.port=${PORT:8081}

# ============================
# DATABASE CONFIG
# ============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/library_management_system?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:akash}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================
# JPA / HIBERNATE
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ============================
# JWT CONFIG
# ============================
jwt.secret=${JWT_SECRET:ZmFrZVNlY3JldEtleUZvckxpYnJhcnlNYW5hZ2VtZW50U3lzdGVtSldUVG9rZW5HZW5lcmF0aW9uMjAyNg==}
# 24 hours in ms
jwt.expiration=86400000

# ============================
# LIBRARY BUSINESS RULES
# ============================
library.fine.per-day=5
library.fine.max=500
library.issue.default-days=14

# ============================
# LOGGING
# ============================
logging.level.org.springframework.security=INFO
logging.level.com.library.lms=INFO